# .github/workflows/deploy-vm.yml
name: Deploy GCP VM

on:
  push:
    paths:
      - 'terraform.tfvars'

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Auth to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Initialize Terraform
      run: terraform init
      
    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"
      
    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
      
    - name: Send Notification
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: VM Deployment Status
        body: Terraform deployment completed
        to: ${{ github.event.head_commit.message }}
        from: GitHub Actions